import { React, Fragment } from "react";
import EducationSection from "./components/education";
import AboutSection from "./components/about";
import ProjectsSection from "./components/projects";
import WorkExpSection from "./components/work_experience";
import "./styles/comm.css";

export default function Portfolio() {
  return (
    <Fragment>
      <p>Lorem ipsum dolor sit amet, consectetur <br />adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat lacus laoreet non curabitur gravida. <br />Luctus accumsan tortor posuere ac ut consequat. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Suscipit adipiscing bibendum est ultricies integer quis auctor. Tristique sollicitudin nibh sit amet commodo nulla. Diam vulputate u<br />t pharetra sit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Mi bibendum neque egestas congue. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis.<br />

Accumsan in nisl nisi sceler<br />isque eu ultrices vitae auctor. Ultricies mi eget mauris pha<br />retra et ultrices. Lacus vel facilisis volutpat est velit egestas dui. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Elementum integer enim neque volutpat. Diam donec adipiscing tristique risus<br />. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Semper feugiat nibh sed pulvinar. Lacus laoreet non curabitur gravida arcu ac tortor. Fames ac turpis egestas integer eget aliquet nibh. Tellus integer feugiat scelerisque varius morbi enim. Fames ac turpis egestas sed. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Malesuada bibendum arcu vitae <br />elementum curabitur vitae nunc sed velit. Ultrices neque ornare aenean euismod elementum. Sit amet consectetur adipiscing elit pellentesque. Et netus et malesuada fames ac.

Nunc pulvinar sapien et ligu<br />la. Risus feugiat in ante metus dictum at tempor commodo ullamcorper. Malesuada fames ac turpis egestas sed. Pharetra mas<br />sa massa ultricies mi. Senectus et netus et malesuada fames ac turp<br />is. Sit amet venenatis urna cursus. Lobortis feugiat viv<br />amus at augue eget arcu dictum varius duis. Quam pellentesque nec nam aliquam sem et tortor. Quis viverra nibh cras pulvinar mattis nunc. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Scelerisque in dictum non consectetur a erat nam at lectus. <br /> elementum tempus egestas sed sed risus pretium.

Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Nunc sed augue lacus viverra vitae congue eu. Aliquet risus feugiat in a<br />nte metus. Tincidunt eget nullam non nisi. Adipiscing bibendum est ultricies integer quis auctor. Netus et malesuada fames ac turpis egestas. Arcu cursus vitae congue mauris rhoncus aenean vel. Consequat ac felis donec et odio. Risus feugiat in a<br />nte metus. Sagittis id consectetur purus ut faucibus. Dictum sit amet justo donec enim diam vulputate ut. Nulla facilisi morbi tempus iaculis. Ultrices dui sapien eget mi proin sed libero enim. Quisque id diam vel quam. Blandit cursus risus at ultrices mi tempus. Vulputate eu scelerisque felis imperdiet.<br />

Viverra suspendisse potenti nullam<br /> ac tortor vitae purus faucibus ornare. Odio aenean sed adipiscing diam donec adipiscing. Urna nec tincidunt praesent semper feugiat. Velit egestas dui id ornare arcu odio ut. Adi<br />piscing commodo elit at imperdiet dui accumsan. Massa placerat duis ultricies lacus sed turpis. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Integer feugiat scelerisque varius morbi. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Eget mauris pharetra et ultrices neque ornare aenean euismod. Ipsum consequat nisl vel pretium lectus quam id. Tortor at auctor urna nunc id cursus metus. Auctor augue mauris augue neque gravida. Aenean sed adipisci<br />ng diam donec. Arcu dictum varius duis at.</p>
<p>Lorem ipsum dolor sit amet, consectetur <br />adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat lacus laoreet non curabitur gravida. <br />Luctus accumsan tortor posuere ac ut consequat. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Suscipit adipiscing bibendum est ultricies integer quis auctor. Tristique sollicitudin nibh sit amet commodo nulla. Diam vulputate u<br />t pharetra sit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Mi bibendum neque egestas congue. Euismod elementum nisi quis eleifend quam adipiscing vitae proin sagittis.<br />

Accumsan in nisl nisi sceler<br />isque eu ultrices vitae auctor. Ultricies mi eget mauris pha<br />retra et ultrices. Lacus vel facilisis volutpat est velit egestas dui. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Elementum integer enim neque volutpat. Diam donec adipiscing tristique risus<br />. Pellentesque elit eget gravida cum sociis natoque penatibus et magnis. Semper feugiat nibh sed pulvinar. Lacus laoreet non curabitur gravida arcu ac tortor. Fames ac turpis egestas integer eget aliquet nibh. Tellus integer feugiat scelerisque varius morbi enim. Fames ac turpis egestas sed. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. Malesuada bibendum arcu vitae <br />elementum curabitur vitae nunc sed velit. Ultrices neque ornare aenean euismod elementum. Sit amet consectetur adipiscing elit pellentesque. Et netus et malesuada fames ac.

Nunc pulvinar sapien et ligu<br />la. Risus feugiat in ante metus dictum at tempor commodo ullamcorper. Malesuada fames ac turpis egestas sed. Pharetra mas<br />sa massa ultricies mi. Senectus et netus et malesuada fames ac turp<br />is. Sit amet venenatis urna cursus. Lobortis feugiat viv<br />amus at augue eget arcu dictum varius duis. Quam pellentesque nec nam aliquam sem et tortor. Quis viverra nibh cras pulvinar mattis nunc. Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Scelerisque in dictum non consectetur a erat nam at lectus. <br /> elementum tempus egestas sed sed risus pretium.

Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Nunc sed augue lacus viverra vitae congue eu. Aliquet risus feugiat in a<br />nte metus. Tincidunt eget nullam non nisi. Adipiscing bibendum est ultricies integer quis auctor. Netus et malesuada fames ac turpis egestas. Arcu cursus vitae congue mauris rhoncus aenean vel. Consequat ac felis donec et odio. Risus feugiat in a<br />nte metus. Sagittis id consectetur purus ut faucibus. Dictum sit amet justo donec enim diam vulputate ut. Nulla facilisi morbi tempus iaculis. Ultrices dui sapien eget mi proin sed libero enim. Quisque id diam vel quam. Blandit cursus risus at ultrices mi tempus. Vulputate eu scelerisque felis imperdiet.<br />

Viverra suspendisse potenti nullam<br /> ac tortor vitae purus faucibus ornare. Odio aenean sed adipiscing diam donec adipiscing. Urna nec tincidunt praesent semper feugiat. Velit egestas dui id ornare arcu odio ut. Adi<br />piscing commodo elit at imperdiet dui accumsan. Massa placerat duis ultricies lacus sed turpis. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Integer feugiat scelerisque varius morbi. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Eget mauris pharetra et ultrices neque ornare aenean euismod. Ipsum consequat nisl vel pretium lectus quam id. Tortor at auctor urna nunc id cursus metus. Auctor augue mauris augue neque gravida. Aenean sed adipisci<br />ng diam donec. Arcu dictum varius duis at.</p>
      <address className="floating-contact">
        <a href="https://github.com/gokulkrh">
          {/* <img src={require("../images/github.png")} alt="" /> */}
          <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 480 512" height="auto" width="1.5em" xmlns="http://www.w3.org/2000/svg"><path d="M186.1 328.7c0 20.9-10.9 55.1-36.7 55.1s-36.7-34.2-36.7-55.1 10.9-55.1 36.7-55.1 36.7 34.2 36.7 55.1zM480 278.2c0 31.9-3.2 65.7-17.5 95-37.9 76.6-142.1 74.8-216.7 74.8-75.8 0-186.2 2.7-225.6-74.8-14.6-29-20.2-63.1-20.2-95 0-41.9 13.9-81.5 41.5-113.6-5.2-15.8-7.7-32.4-7.7-48.8 0-21.5 4.9-32.3 14.6-51.8 45.3 0 74.3 9 108.8 36 29-6.9 58.8-10 88.7-10 27 0 54.2 2.9 80.4 9.2 34-26.7 63-35.2 107.8-35.2 9.8 19.5 14.6 30.3 14.6 51.8 0 16.4-2.6 32.7-7.7 48.2 27.5 32.4 39 72.3 39 114.2zm-64.3 50.5c0-43.9-26.7-82.6-73.5-82.6-18.9 0-37 3.4-56 6-14.9 2.3-29.8 3.2-45.1 3.2-15.2 0-30.1-.9-45.1-3.2-18.7-2.6-37-6-56-6-46.8 0-73.5 38.7-73.5 82.6 0 87.8 80.4 101.3 150.4 101.3h48.2c70.3 0 150.6-13.4 150.6-101.3zm-82.6-55.1c-25.8 0-36.7 34.2-36.7 55.1s10.9 55.1 36.7 55.1 36.7-34.2 36.7-55.1-10.9-55.1-36.7-55.1z"></path></svg>
        </a>
        <a href="">
          {/* <img src={require("../images/linkedinBG.png")} alt="" /> */}
          <svg stroke="currentColor" fill="currentColor" strokeWidth="0" viewBox="0 0 448 512" height="auto" width="1.5em" xmlns="http://www.w3.org/2000/svg"><path d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"></path></svg>
        </a>
      </address>
      <AboutSection />
      <WorkExpSection />
      <ProjectsSection />
      <EducationSection />
    </Fragment>
  );
}
